# Generated by Django 3.2.18 on 2023-03-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='address',
            field=models.CharField(blank=True, max_length=120, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='phone',
            field=models.IntegerField(blank=True, max_length=15, verbose_name='Contact Phone'),
        ),
    ]
